run_sparse: true
run_mesh: true
run_gaussian: true
run_gs_to_pc: true
use_gps: true
quality_preset: medium
feature_type: sift
sh_degree: 1
algorithms:
  sfm: opensfm
  reconstruction: opensplat
  sfm_docker_image: opendronemap/odm:gpu
  reconstruction_docker_image: opensplat-dev:latest
  gs_to_pc_docker_image: gs2pc-tool:latest
params:
  opensplat:
    iterations: 10000
    auto-stop-on-same-size: true
    save-every: 2000
